services:
  - type: web
    name: eclisse-ecommerce
    env: php
    buildCommand: composer install
    startCommand: heroku-php-apache2
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: BASE_URL
        value: https://your-app-name.onrender.com
      - key: WHATSAPP_NUMBER
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: NOTIFICATION_EMAIL
        sync: false